# Generated by Django 2.1.7 on 2019-03-20 22:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190314_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.page_image_file_path),
        ),
    ]
