# Generated by Django 2.1.7 on 2019-03-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_provider_providerservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='slug',
        ),
        migrations.AddField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
