# Generated by Django 2.1.7 on 2019-04-05 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190405_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.Provider'),
        ),
    ]
