# Generated by Django 2.1.7 on 2019-04-06 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_provider_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='admin_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
