# Generated by Django 2.1.7 on 2019-04-06 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_provider_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='provider_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
