# Generated by Django 2.1.8 on 2019-04-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190408_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_anon',
            field=models.BooleanField(default=False),
        ),
    ]
