# Generated by Django 2.1.8 on 2019-04-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190419_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='categories',
            field=models.ManyToManyField(to='core.ProviderCategory'),
        ),
    ]
