# Generated by Django 2.1.8 on 2019-04-25 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190420_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reply_set', to='core.Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='categories',
            field=models.ManyToManyField(null=True, to='core.ReviewCategory'),
        ),
        migrations.AlterField(
            model_name='review',
            name='confirmation_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(null=True, to='core.HashTag'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
