# Generated by Django 2.1.8 on 2019-04-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190425_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='categories',
            field=models.ManyToManyField(to='core.ReviewCategory'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(to='core.HashTag'),
        ),
    ]
