# Generated by Django 2.1.8 on 2019-05-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20190430_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlog',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='ip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
